import { Metadata } from "next";
import './globals.css';
// import {ErrorWrapper} from "./error-wrapper";

export const metadata: Metadata = {
  title: {
    default: "My Next.js App",
    template: "%s | My Next.js App",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang= "en" >
    <body>
    <header style={ { backgroundColor: "#f0f0f0", padding: "10px" } }>
      <h1>My Next.js App </h1>
        </header>
  {/* <ErrorWrapper> */ }
  { children }
  {/* </ErrorWrapper> */ }
  <footer
          style={
    {
      backgroundColor: "#f0f0f0",
        padding: "10px",
          marginTop: "20px",
          }
  }
        >
    <p>© 2024 My Next.js App </p>
      </footer>
      </body>
      </html>
  );
}
